export const ADD_TO_CART_REQ = "ADD_TO_CART_REQ";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const ADD_TO_CART_RESET = "ADD_TO_CART_RESET";

export const GET_MY_CART_REQ = "GET_MY_CART_REQ";
export const GET_MY_CART_SUCCESS = "GET_MY_CART_SUCCESS";
export const GET_MY_CART_FAIL = "GET_MY_CART_FAIL";

export const DELETE_ITEM_REQ = "DELETE_ITEM_REQ";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
export const DELETE_ITEM_RESET = "DELETE_ITEM_RESET";

export const DELETE_MY_CART_REQ = "DELETE_MY_CART_REQ";
export const DELETE_MY_CART_SUCCESS = "DELETE_MY_CART_SUCCESS";
export const DELETE_MY_CART_FAIL = "DELETE_MY_CART_FAIL";
export const DELETE_MY_CART_RESET = "DELETE_MY_CART_RESET";
