export const CREATE_PAYMENT_REQ = "CREATE_PAYMENT_REQ";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = "CREATE_PAYMENT_FAIL";
export const CREATE_PAYMENT_RESET = "CREATE_PAYMENT_RESET";

export const UPDATE_PAYMENT_REQ = "UPDATE_PAYMENT_REQ";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAIL = "UPDATE_PAYMENT_FAIL";
export const UPDATE_PAYMENT_RESET = "UPDATE_PAYMENT_RESET";

export const GET_ALL_PAYMENT_REQ = "GET_ALL_PAYMENT_REQ";
export const GET_ALL_PAYMENT_SUCCESS = "GET_ALL_PAYMENT_SUCCESS";
export const GET_ALL_PAYMENT_FAIL = "GET_ALL_PAYMENT_FAIL";

export const GET_REPORT_PAYMENT_REQ = "GET_REPORT_PAYMENT_REQ";
export const GET_REPORT_PAYMENT_SUCCESS = "GET_REPORT_PAYMENT_SUCCESS";
export const GET_REPORT_PAYMENT_FAIL = "GET_REPORT_PAYMENT_FAIL";

export const MY_PAYMENT_REQ = "MY_PAYMENT_REQ";
export const MY_PAYMENT_SUCCESS = "MY_PAYMENT_SUCCESS";
export const MY_PAYMENT_FAIL = "MY_PAYMENT_FAIL";

export const DETAIL_PAYMENT_REQ = "DETAIL_PAYMENT_REQ";
export const DETAIL_PAYMENT_SUCCESS = "DETAIL_PAYMENT_SUCCESS";
export const DETAIL_PAYMENT_FAIL = "DETAIL_PAYMENT_FAIL";

export const GET_TOKEN_REQ = "GET_TOKEN_REQ";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAIL = "GET_TOKEN_FAIL";
export const GET_TOKEN_RESET = "GET_TOKEN_RESET";
