export const GET_PROVINCES_REQ = "GET_PROVINCES_REQ";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_FAIL = "GET_PROVINCES_FAIL";

export const GET_CITIES_REQ = "GET_CITIES_REQ";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";
export const GET_CITIES_FAIL = "GET_CITIES_FAIL";

export const GET_COURIERS_REQ = "GET_COURIERS_REQ";
export const GET_COURIERS_SUCCESS = "GET_COURIERS_SUCCESS";
export const GET_COURIERS_FAIL = "GET_COURIERS_FAIL";
