export const GET_DATA_STORE_REQ = "GET_DATA_STORE_REQ";
export const GET_DATA_STORE_SUCCESS = "GET_DATA_STORE_SUCCESS";
export const GET_DATA_STORE_FAIL = "GET_DATA_STORE_FAIL";

export const UPDATE_STORE_REQ = "UPDATE_STORE_REQ";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";
export const UPDATE_STORE_RESET = "UPDATE_STORE_RESET";
