export const MY_ORDERS_REQ = "MY_ORDERS_REQ";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const MY_ORDER_DETAIL_REQ = "MY_ORDER_DETAIL_REQ";
export const MY_ORDER_DETAIL_SUCCESS = "MY_ORDER_DETAIL_SUCCESS";
export const MY_ORDER_DETAIL_FAIL = "MY_ORDER_DETAIL_FAIL";

export const GET_ORDERS_REQ = "GET_ORDERS_REQ";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_ORDER_DETAIL_REQ = "GET_ORDER_DETAIL_REQ";
export const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_FAIL = "GET_ORDER_DETAIL_FAIL";

export const UPDATE_ORDER_REQ = "UPDATE_ORDER_REQ";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";

export const DELETE_ORDER_REQ = "DELETE_ORDER_REQ";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
