export const USER_REGISTER_REQ = "USER_REGISTER_REQ";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const GOOGLE_REGISTER_REQ = "GOOGLE_REGISTER_REQ";
export const GOOGLE_REGISTER_SUCCESS = "GOOGLE_REGISTER_SUCCESS";
export const GOOGLE_REGISTER_FAIL = "GOOGLE_REGISTER_FAIL";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GOOGLE_LOGIN_REQ = "GOOGLE_LOGIN_REQ";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAIL = "GOOGLE_LOGIN_FAIL";

export const USER_LOAD_REQ = "USER_LOAD_REQ";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";

export const USER_LOGOUT_REQ = "USER_LOGOUT_REQ";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const RESET_STORE = "RESET_STORE";

export const CHANGE_PROFILE_REQ = "CHANGE_PROFILE_REQ";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAIL = "CHANGE_PROFILE_FAIL";
export const CHANGE_PROFILE_RESET = "CHANGE_PROFILE_RESET";

export const CHANGE_PASSWORD_REQ = "CHANGE_PASSWORD_REQ";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_PASSWORD_RESET = "CHANGE_PASSWORD_RESET";

export const SEND_EMAIL_REQ = "SEND_EMAIL_REQ";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL";
export const SEND_EMAIL_RESET = "SEND_EMAIL_RESET";

export const RESET_PASSWORD_REQ = "RESET_PASSWORD_REQ";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";

export const GET_USERS_REQ = "GET_USERS_REQ";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const DELETE_USERS_REQ = "DELETE_USERS_REQ";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
export const DELETE_USERS_RESET = "DELETE_USERS_RESET";
