export const GET_PRODUCTS_REQ = "GET_PRODUCTS_REQ";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_DETAIL_PRODUCT_REQ = "GET_DETAIL_PRODUCT_REQ";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAIL = "GET_DETAIL_PRODUCT_FAIL";

export const ADD_PRODUCT_REQ = "ADD_PRODUCT_REQ";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const ADD_PRODUCT_RESET = "ADD_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQ = "UPDATE_PRODUCT_REQ";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const UPLOAD_FILE_REQ = "UPLOAD_FILE_REQ";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL";
export const UPLOAD_FILE_RESET = "UPLOAD_FILE_RESET";

export const DELETE_PRODUCT_REQ = "DELETE_PRODUCT_REQ";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const DELETE_PRODUCTS_REQ = "DELETE_PRODUCTS_REQ";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAIL = "DELETE_PRODUCTS_FAIL";
export const DELETE_PRODUCTS_RESET = "DELETE_PRODUCTS_RESET";

export const CREATE_REVIEW_REQ = "CREATE_REVIEW_REQ";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";
